-- Create post_versions table
CREATE TABLE IF NOT EXISTS post_versions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT,
    version_no INT NOT NULL,
    title VARCHAR(500),
    content TEXT,
    edited_by INT,
    change_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create unique index on post_id and version_no combination
CREATE UNIQUE INDEX IF NOT EXISTS idx_post_versions_post_id_version_no ON post_versions(post_id, version_no);

-- Add comment
COMMENT ON TABLE post_versions IS 'Stores historical versions of posts for audit and rollback purposes';
