-- Create tags table
CREATE TABLE IF NOT EXISTS tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT,
    name VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    usage_count INT DEFAULT 0,
    embedding vector(1536),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_tags_slug ON tags(slug);

-- Note: Vector index will be created separately after pgvector extension is enabled
-- CREATE INDEX IF NOT EXISTS idx_tags_embedding ON tags USING IVFFLAT (embedding);

-- Add comment
COMMENT ON TABLE tags IS 'Tags for categorizing and organizing posts';
