-- Create posts table
CREATE TABLE IF NOT EXISTS posts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INT,
    title VARCHAR(500) NOT NULL,
    slug VARCHAR(500) UNIQUE NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    content_embedding vector(1536),
    thumbnail_url VARCHAR(500),
    category_id INT,
    sub_category_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    is_featured BOOLEAN DEFAULT false,
    quality_score DECIMAL(3,2),
    readability_score DECIMAL(3,2),
    created_by INT,
    view_count INT DEFAULT 0,
    like_count INT DEFAULT 0,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_category_id ON posts(category_id);
CREATE INDEX IF NOT EXISTS idx_posts_tenant_id ON posts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);

-- Note: Vector index will be created separately after pgvector extension is enabled
-- CREATE INDEX IF NOT EXISTS idx_posts_content_embedding ON posts USING IVFFLAT (content_embedding);

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';
