-- Create post_tags junction table
CREATE TABLE IF NOT EXISTS post_tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT,
    tag_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create unique index to prevent duplicate tag assignments
CREATE UNIQUE INDEX IF NOT EXISTS idx_post_tags_post_id_tag_id ON post_tags(post_id, tag_id);

-- Add comment
COMMENT ON TABLE post_tags IS 'Junction table linking posts to tags (many-to-many relationship)';
