-- Migration: Create tags table for content tagging
-- This table doesn't exist yet, so we create it from scratch

CREATE TABLE IF NOT EXISTS tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT,
    name VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    usage_count INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Note: Vector embedding column requires pgvector extension
-- Uncomment the following line after installing pgvector extension:
-- ALTER TABLE tags ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_tags_slug ON tags(slug);
CREATE INDEX IF NOT EXISTS idx_tags_tenant_id ON tags(tenant_id);

-- Note: Vector index will be created separately after pgvector extension is enabled
-- CREATE INDEX IF NOT EXISTS idx_tags_embedding ON tags USING IVFFLAT (embedding);

-- Add comment
COMMENT ON TABLE tags IS 'Tags for categorizing and organizing posts';
