-- Migration: Create posts table
-- This migration creates the posts table for blog posts and articles

CREATE TABLE IF NOT EXISTS posts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP,
  
  -- Order
  order_no INT NOT NULL UNIQUE,
  
  -- Content
  title VARCHAR(500) NOT NULL,
  slug VARCHAR(500) UNIQUE NOT NULL,
  summary TEXT,
  content TEXT NOT NULL,
  thumbnail VARCHAR(500),
  
  -- Categorization
  category_id INT NOT NULL,
  sub_category_id INT,
  
  -- SEO
  meta_title VARCHAR(500),
  meta_description TEXT,
  keywords TEXT,
  og_image VARCHAR(500),
  
  -- Status & Visibility
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  is_public BOOLEAN DEFAULT true,
  is_featured BOOLEAN DEFAULT false,
  is_pinned BOOLEAN DEFAULT false,
  
  -- Timestamps
  published_at TIMESTAMP,
  archived_at TIMESTAMP,
  
  -- Audit
  created_by INT NOT NULL,
  updated_by INT,
  
  -- Stats
  view_count INT DEFAULT 0,
  
  -- Version tracking
  version INT DEFAULT 1
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_posts_deleted_at ON posts(deleted_at);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_category_id ON posts(category_id);
CREATE INDEX IF NOT EXISTS idx_posts_sub_category_id ON posts(sub_category_id);
CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_is_featured ON posts(is_featured);
CREATE INDEX IF NOT EXISTS idx_posts_created_by ON posts(created_by);

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for posts
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at 
    BEFORE UPDATE ON posts
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
