-- Migration: Create post_versions table
-- This migration creates the post_versions table for tracking post history

CREATE TABLE IF NOT EXISTS post_versions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP,
  
  post_id INT NOT NULL,
  version_no INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,
  edited_by INT NOT NULL,
  change_note TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_post_versions_deleted_at ON post_versions(deleted_at);
CREATE INDEX IF NOT EXISTS idx_post_versions_post_id ON post_versions(post_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_post_versions_post_id_version_no ON post_versions(post_id, version_no);
CREATE INDEX IF NOT EXISTS idx_post_versions_edited_by ON post_versions(edited_by);

-- Add comment
COMMENT ON TABLE post_versions IS 'Stores historical versions of posts for audit and rollback purposes';
