-- Migration: Create discussion_replies table
CREATE TABLE IF NOT EXISTS discussion_replies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

  tenant_id INT REFERENCES tenants(id),
  discussion_id INT NOT NULL REFERENCES discussions(id),
  user_id INT NOT NULL REFERENCES users(id),
  parent_id INT REFERENCES discussion_replies(id),

  content TEXT NOT NULL,

  upvote_count INT DEFAULT 0,
  is_solution BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_discussion_replies_discussion_id ON discussion_replies(discussion_id);
CREATE INDEX IF NOT EXISTS idx_discussion_replies_user_id ON discussion_replies(user_id);
CREATE INDEX IF NOT EXISTS idx_discussion_replies_parent_id ON discussion_replies(parent_id);
CREATE INDEX IF NOT EXISTS idx_discussion_replies_is_solution ON discussion_replies(is_solution);

DROP TRIGGER IF EXISTS update_discussion_replies_updated_at ON discussion_replies;
CREATE TRIGGER update_discussion_replies_updated_at
    BEFORE UPDATE ON discussion_replies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
