-- Migration: Create categories table and Add tenant/visual fields
-- This migration ensures the categories table exists and has all necessary columns

CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INT,
    parent_id INT,
    slug VARCHAR(255) UNIQUE NOT NULL,
    label VARCHAR(255) NOT NULL,
    description TEXT,
    icon VARCHAR(100),
    color VARCHAR(50),
    created_by INT,
    creator_id INT,
    updated_by INT,
    approved_by INT,
    deleted_by INT,
    approved_at TIMESTAMP,
    deleted_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'approved',
    meta JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Ensure all columns exist (for production databases where table already exists)
ALTER TABLE categories ADD COLUMN IF NOT EXISTS tenant_id INT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon VARCHAR(100);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS color VARCHAR(50);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS creator_id INT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_by INT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS approved_by INT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted_by INT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS meta JSONB;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

-- Note: Vector embedding column requires pgvector extension
-- Extension should be created before adding the column
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        CREATE EXTENSION IF NOT EXISTS vector;
    END IF;
END $$;

ALTER TABLE categories ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Add foreign key constraints if they don't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_categories_tenant'
    ) THEN
        ALTER TABLE categories ADD CONSTRAINT fk_categories_tenant 
            FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_categories_parent'
    ) THEN
        ALTER TABLE categories ADD CONSTRAINT fk_categories_parent 
            FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_categories_created_by'
    ) THEN
        ALTER TABLE categories ADD CONSTRAINT fk_categories_created_by 
            FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Ensure indexes exist
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug);
CREATE INDEX IF NOT EXISTS idx_categories_tenant_id ON categories(tenant_id);

-- Note: Vector index will be created separately after pgvector extension is enabled
-- CREATE INDEX IF NOT EXISTS idx_categories_embedding ON categories USING IVFFLAT (embedding);
