-- Migration: Create tenants table and Add AI quota fields
-- This migration ensures the tenants table exists and has all necessary columns

CREATE TABLE IF NOT EXISTS tenants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    domain VARCHAR(255) UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    plan VARCHAR(20) NOT NULL DEFAULT 'free',
    settings JSONB,
    meta JSONB,
    ai_quota_monthly INT DEFAULT 1000,
    ai_usage_current INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Ensure all columns exist (for production databases where table already exists)
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS settings JSONB;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS meta JSONB;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS ai_quota_monthly INT DEFAULT 1000;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS ai_usage_current INT DEFAULT 0;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan VARCHAR(20) DEFAULT 'free';

-- Ensure indexes exist
CREATE INDEX IF NOT EXISTS idx_tenants_slug ON tenants(slug);
CREATE INDEX IF NOT EXISTS idx_tenants_domain ON tenants(domain);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for tenants if not exists
DROP TRIGGER IF EXISTS update_tenants_updated_at ON tenants;
CREATE TRIGGER update_tenants_updated_at 
    BEFORE UPDATE ON tenants
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Update existing records to have default AI quota values
UPDATE tenants 
SET ai_quota_monthly = 1000, ai_usage_current = 0 
WHERE ai_quota_monthly IS NULL OR ai_usage_current IS NULL;
