# .github/workflows/deploy-cortex.yml
name: Build and Deploy Cortex

on:
  push:
    branches:
      - master
    paths:
      - 'cortex/**'  # Only trigger if cortex folder changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Cortex image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cortex:latest ./cortex

      # 5. Push Docker image
      - name: Push Cortex image
        run: |
          docker push ghcr.io/${{ github.repository }}/cortex:latest
