name: Go Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Run Go Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.2"

            - name: Cache Go modules and build (reusable)
              uses: ./.github/actions/go-cache

            - name: Run tests in all services
              run: |
                  for dir in cortex skeleton ecommerce; do
                    echo "🔍 Testing service: $dir"
                    cd $dir
                    go mod tidy
                    go test ./... -v
                    cd -
                  done
